### ISSUE TITLE
Github branch can't be cloned and then uploaded on Heroku

### ISSUE THREAD

**Issue by winstonma** [chrisckchang/mean-contactlist-angular2#6]
After cloning the branch and added all files on Heroku, I got the error `Cannot read property 'config' of null` during the `git clone heroic master` step. After searching web for a while I found that the problem can be solved by creating a new project (using `ng new`) and copy the '.angular-cli.json' into your branch, then the project can be deployed and everything works.

**Comment by tfogo** [comment]
Hey @winstonma, sorry for the late response here. Thanks for letting us know about the issue. Unfortunately I wasn't able to reproduce the issue. Reading [this issue on angular-cli](https://github.com/angular/angular-cli/issues/4736) makes it look like it might be a problem due to using an older version of angular-cli. Let me know if you think it's something more serious.

We'll keep an eye out for this problem in the future.
