### ISSUE TITLE
contact.service.ts Promise issue

### ISSUE THREAD

**Issue by rae89** [chrisckchang/mean-contactlist-angular2#7]
Hello, I am receiving the following types of error in the contact.service.ts script. I am receiving four different errors of these type one for each of the following methods getContacts(), createContact(...), deleteContact(...), updateContact(...).  I am using visual code, which is how I identified the error below.

severity: 'Error'
message: 'Type 'Promise<void | Contact[]>' is not assignable to type 'Promise<Contact[]>'.
  Type 'void | Contact[]' is not assignable to type 'Contact[]'.
    Type 'void' is not assignable to type 'Contact[]'.'
at: '17,7'
source: 'ts'

**Comment by tfogo** [comment]
Hey,

Good catch! Looks like `handleError` returns `<void>`. Since `handleError` catches errors in the promises, the promise types should be `<void | Contact[]>` etc.

So you should be safe to just edit your file to correct this. (See the fix [here](https://github.com/chrisckchang/mean-contactlist-angular2/pull/8/files))

@chrisckchang, PR to fix this incoming.

**Comment by chrisckchang** [comment]
@rae89 PR here: https://github.com/chrisckchang/mean-contactlist-angular2/pull/8. can you please confirm it works for you?
