### ISSUE TITLE
package.json- "postinstall":"ng build" build failed

### ISSUE THREAD

**Issue by rae89** [chrisckchang/mean-contactlist-angular2#9]
Hello, I am try to follow the directions on how to setup the mean contact list from the heroku link: https://devcenter.heroku.com/articles/mean-apps-restful-api#define-the-contact-class

I ran into another issue when trying to `git push heroku master`, where the build fails at the `"postinstall":"ng build"` step of the package.json file.  When I do not include "postinstall":"ng build" in the package.json it was able to build, but when I ran `heroku open` none of the angular code appeared and the browser just outputted the following: **Cannot GET /**.  

The build error message when trying to build with `"postinstall":"ng build"` is as follows"

> remote: -----> Building dependencies
> remote:        Installing node modules (package.json + package-lock)
> remote:        
> remote:        > mean-contactlist-angular2@0.0.0 postinstall /tmp/build_7139d1c89bf1b25a5122707c093fcaee
> remote:        > ng build
> remote:        
> remote:        sh: 1: ng: not found
> remote:        npm ERR! file sh
> remote:        npm ERR! code ELIFECYCLE
> remote:        npm ERR! errno ENOENT
> remote:        npm ERR! syscall spawn
> remote:        npm ERR! mean-contactlist-angular2@0.0.0 postinstall: `ng build`
> remote:        npm ERR! spawn ENOENT
> remote:        npm ERR!
> remote:        npm ERR! Failed at the mean-contactlist-angular2@0.0.0 postinstall script.
> remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> remote:        
> remote:        npm ERR! A complete log of this run can be found in:
> remote:        npm ERR!     /app/.npm/_logs/2017-08-02T20_55_51_819Z-debug.log
> remote: 
> remote: -----> Build failed
> remote:        
> remote:        We're sorry this build is failing! You can troubleshoot common issues here:
> remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
> remote:        
> remote:        If you're stuck, please submit a ticket so we can help:
> remote:        https://help.heroku.com/
> remote:        
> remote:        Love,
> remote:        Heroku
> remote:        
> remote:  !     Push rejected, failed to compile Node.js app.
> remote: 
> remote:  !     Push failed
> remote: Verifying deploy...
> remote: 
> remote: !	Push rejected to infinite-gorge-38681.
> remote: 
> To https://git.heroku.com/infinite-gorge-38681.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/infinite-gorge-38681.git'

**Comment by tfogo** [comment]
Hi @rae89, sorry to hear you're having trouble. Please can you share your `package.json` and `package-lock.json` (if you have one)?

**Comment by rae89** [comment]
`package.json`

```
{
  "name": "mean-contactlist-angular2",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall":"ng build"

  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "body-parser": "^1.17.2",
    "core-js": "^2.4.1",
    "express": "^4.15.3",
    "mongodb": "^2.2.30",
    "rxjs": "^5.4.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.6",
    "@angular/compiler-cli": "^4.3.2",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  },

    "engines": {
    "node": "8.2.1",
    "npm": "5.3.0"
  }
}

```

**Comment by rae89** [comment]
[package-lock.json.zip](https://github.com/chrisckchang/mean-contactlist-angular2/files/1195920/package-lock.json.zip)

**Comment by tfogo** [comment]
Thanks!

The issue here is that `@angular/cli` and `@angular/compiler-cli` are in your `devDependencies` instead of your `dependencies`. `@angular/language-service` might cause an issue too - might be best to put all `@angular` packages into your `dependencies`.

You can fix this by running:

```
$ npm install --save @angular/cli @angular/compiler-cli @angular/language-service
```

Let me know if that fixes it.

The reason this causes an issue on Heroku is that the `NODE_ENV` environment variable is set to `production` by default. When that's the case, running `npm install` will only install your dependencies and will ignore your dev dependencies. So Heroku isn't installing the angular cli and the postinstall script gets confused.

It looks like running `ng new` puts those packages in your devDependencies by default for some reason - so we'll look into clarifying the tutorial. Thanks for the feedback!

**Comment by rae89** [comment]
Thanks! That seems to have fixed the issue with the building.  But I still cannot get the app to run once I run `heroku open`, the heroku link try's to load, but only a Loading... browser page appears.  Should the app work when I run `npm start`, because it currently throws errors.  But I assume the error is due to the mongodb db being on heroku.

> mean-contactlist-angular2@0.0.0 start *****/Documents/mean-contactlist-angular2
> node server.js
> 
> url.js:102
>     throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
>     ^
> 
> TypeError: Parameter "url" must be a string, not undefined
>     at Url.parse (url.js:102:11)
>     at Object.urlParse [as parse] (url.js:96:5)
>     at module.exports (*****/Documents/mean-contactlist-angular2/node_modules/mongodb/lib/url_parser.js:16:23)
>     at connect (*****/Documents/mean-contactlist-angular2/node_modules/mongodb/lib/mongo_client.js:482:16)
>     at Function.MongoClient.connect (*****/Documents/mean-contactlist-angular2/node_modules/mongodb/lib/mongo_client.js:246:3)
>     at Object.<anonymous> (*****/Documents/mean-contactlist-angular2/server.js:19:21)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mean-contactlist-angular2@0.0.0 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the mean-contactlist-angular2@0.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     *****/.npm/_logs/2017-08-03T15_20_46_155Z-debug.log

**Comment by tfogo** [comment]
Hey,

This looks to me like it might be a problem with your `MONGODB_URI` env variable not being set. You can see you config vars by running `heroku config` on the command line or by looking under _Config Variables_ in the _Settings_ tab of your app on the Heroku website.

If `MONGODB_URI` isn't set, you can add a free mLab Sandbox Database to your app using the website or by running `heroku addons:create mongolab:sandbox`. This should automatically set your `MONGODB_URI`. It should look something like: `mongodb://heroku_12345678:random_password@ds029017.mLab.com:29017/heroku_12345678`

Let us know if that was the issue. Hope it's working out!

**Comment by rae89** [comment]
I ran `heroku config` and the URI is already set.

**Comment by tfogo** [comment]
Hmmm... If you're running `npm start` on your local machine, `MONGODB_URI` might not be defined locally? But if you're getting the same error in the heroku log, I'm not sure what the issue might be. If you want to upload your project to GitHub, I'm happy to take a look and try to reproduce the issue if that would be helpful.

**Comment by timpoe** [comment]
@tfogo - I think I'm probably having the same issue @rae89 eventually ran into after he fixed his build problem by moving the dependencies). 

It builds, i can curl and use the api just fine but the actual web display is just blank. I'm building from scratch, comparing with diff at every step, squashed many bugs along the way. But finally at the very end it's not displaying which is a little disappointing. Mongo is connected and happy according to mlab dashboard and ability to crud with the rest api.

I'd bet it's just some small angular thing but I did the template to learn more node/mongo/express and not to take a dive into angular :/  

anyway, just wanted to let you know if you build from scratch you might be able to see what the same issue is. here is my repo in case that's helpful for debugging or maybe I made an error because angular is new to me

https://github.com/timpoe/heroku-mean

**Comment by tfogo** [comment]
@timpoe I think the issue is you don't have the `FormsModule` and `HttpModule` in your `app.module.ts`. You have to import them and list them in the imports array. See [here](https://github.com/chrisckchang/mean-contactlist-angular2/blob/master/src/app/app.module.ts#L3-L4) and [here](https://github.com/chrisckchang/mean-contactlist-angular2/blob/master/src/app/app.module.ts#L18-L19). I cloned your project and when I made that change it worked. If you're still having issues, can you open a new issue and copy in any error messages you're seeing? I think this is a different problem from this issue.

Also, I think you're right that this step is missing from the tutorial. We'll do another pass through and double check everything that's in there is correct and complete. Thanks for letting us know and sharing your code.
